### ISSUE TITLE
Targeting engine with Project->Build does not close open webviews

### ISSUE THREAD

**Issue by subsoap** [defold/extension-webview#10]
Not sure if this is possible... have to force close app to get webviews that are stuck open to close.

**Comment by britzl** [comment]
Could you call webview.destroy(webview_id) from the final() function of a script to close them?

We can probably let the extension keep track of created webviews and in WebView_AppFinalize() we destroy all webviews.

**Comment by subsoap** [comment]
>in WebView_AppFinalize() we destroy all webviews

For sure should work this way.

**Comment by britzl** [comment]
Ah, yes, this is how it works already: https://github.com/defold/extension-webview/blob/master/webview/src/webview_android.cpp#L424-L443

Nest step is to add logging to figure out what happens when you target the engine and relaunch. Isn't app_finalize called?

**Comment by subsoap** [comment]
I added this, and it does show up in the log, but the active webview does  not close. Additionally using IAC to close the active webview does not work, I have to force close the app.

https://github.com/subsoap/extension-webview/blob/master/webview/src/webview_android.cpp#L426

``` INFO:WEBVIEWEXTERNAL: Platform Finalize Called ```

**Comment by subsoap** [comment]
![log](https://user-images.githubusercontent.com/409170/74310767-c5253c00-4d22-11ea-9b72-4d987dc39d47.png)
It looks like this, might be a clue.

**Comment by britzl** [comment]
Please test: https://github.com/defold/extension-webview/archive/Issue-10-destroy-webviews-on-finalize.zip

**Comment by subsoap** [comment]
@britzl Tested, open webviews now close on Project->Build when targeting device. ✨
