### ISSUE TITLE
New webviews don't open in long running app on Android

### ISSUE THREAD

**Issue by subsoap** [defold/extension-webview#12]
I've seen this but don't have more info / reproduction steps yet. Previous webviews do appear to be destroyed / if I spam create/open/destroy normally it works fine, but leaving app running for a long time and then trying to open doesn't seem to work. I'll test more and see if still happens.

**Comment by britzl** [comment]
Yes, please provide more information and clear steps to reproduce. We do not have enough information to act upon yet.

**Comment by subsoap** [comment]
Found the issue, which was user error. I had two different places where webviews were able to be created after I generalized it and forgot to disable the old place which also never destroyed its webviews. 😇

```
ERROR:WEBVIEWEXTERNAL: Max number of webviews already opened: 4
ERROR:WEBVIEWEXTERNAL: Platform_SetPosition: Invalid webview_id: -1
ERROR:WEBVIEWEXTERNAL: Max number of webviews already opened: 4
ERROR:WEBVIEWEXTERNAL: Platform_SetPosition: Invalid webview_id: -1
ERROR:WEBVIEWEXTERNAL: Max number of webviews already opened: 4
ERROR:WEBVIEWEXTERNAL: Platform_OpenRaw: Invalid webview_id: -1
```

**Comment by britzl** [comment]
Yay, happy to hear that you found the reason!
