### ISSUE TITLE
webview.open_raw() not working on iOS?

### ISSUE THREAD

**Issue by subsoap** [defold/extension-webview#13]
![2020-02-11 22_06_26-Slack _ social _ Defold Hangout](https://user-images.githubusercontent.com/409170/74307661-d407f080-4d1a-11ea-8625-12d3a9a6ddde.png)

It does work for me for sure on Android. I have not personally tested it on iOS.

**Comment by dapetcu21** [comment]
Yes. I couldn't get it to work on iOS. Calling `open_raw()` would just not do anything. `open()` works though.

**Comment by britzl** [comment]
It would make sense to fix #6 and this one at the same time.
