### ISSUE TITLE
Game gets APP_CMD_LOST_FOCUS when showing webview on Android

### ISSUE THREAD

**Issue by dapetcu21** [defold/extension-webview#26]
OnePlus One on Android 6.0.1
WebView with Chrome/44.0.2403.119

The game gets `APP_CMD_LOST_FOCUS` right before `Java_com_defold_webview_WebViewJNI_onPageFinished()` gets called. The engine then freezes before `Platform_Update()` gets the chance to process the event from the queue and send it to Lua.

So you can show a web view, but you can't ever close it, since you can't process events coming from it or eval JS, since Lua is paused.

I added some dmLogs to showcase this:

```
12-24 23:18:02.789  4745  4766 I defold  : INFO:WEBVIEWEXTERNAL: update
12-24 23:18:02.805  4745  4766 I defold  : INFO:WEBVIEWEXTERNAL: update
12-24 23:18:02.823  4745  4766 I defold  : INFO:WEBVIEWEXTERNAL: update
12-24 23:18:02.834  4745  4745 V threaded_app: WindowFocusChanged: 0xb4d3e2a0 -- 0
12-24 23:18:02.834  4745  4764 V glfw-android: handleCommand: APP_CMD_LOST_FOCUS
12-24 23:18:02.877  4745  4745 W BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 4745
12-24 23:18:04.914  4745  4745 I defold  : INFO:WEBVIEWEXTERNAL: onPageFinished
```

My guess is that Android wants to pause the game's activity that's in the background and invisible. I have no idea how to prevent this.

UPDATE: I've seen the same behaviour even when the webview doesn't occupy the whole screen.

Unfortunately, this is blocking us 😞. The only workaround I found was `engine.run_while_iconified = 1`, but that is not a real solution, since it uses battery even when the app is in the background.

**Comment by britzl** [comment]
I think we may need some input from @JCash here. He's wrestled quite a bit with the Android lifecycle for the engine.

**Comment by AGulev** [comment]
@britzl yes, it's related to lifecycle.
also when game shows ADS to the user, game can't recieve callbacks because extension `update()` - doesn't work

**Comment by willemt** [comment]
I'm experiencing this issue too.
Device: Pixel2 XL, Android 10
Defold: 1.2.190

**Comment by britzl** [comment]
We're discussing ways in which to work around this. This not only affects this extension but also other extensions using a webview (for instance ads extensions). We may have to consider some way to keep parts of the engine running even when it is out of focus.

**Comment by any-me** [comment]
_new to defold, so i might get wrong about defold engine rendering on android_ 

Android [WebView](https://developer.android.com/reference/android/webkit/WebView.html) doesn't inherits from [GLSurfaceView](https://developer.android.com/reference/android/opengl/GLSurfaceView) that defold [use](https://github.com/defold/defold/blob/f89acfb9d7a60eaefa540af05dbb37cfa4148226/engine/glfw/lib/android/android_window.c?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L333)

Instancing WebView will create a new SurfaceView on top, which will cause discussed behavior.

Possible solution: "hole-punching" as mentioned at [SurfaceView](https://developer.android.com/reference/android/view/SurfaceView) reference

> The surface is Z ordered so that it is behind the window holding its SurfaceView; the SurfaceView punches a hole in its window to allow its surface to be displayed. The view hierarchy will take care of correctly compositing with the Surface any siblings of the SurfaceView that would normally appear on top of it. This can be used to place overlays such as buttons on top of the Surface, though note however that it can have an impact on performance since a full alpha-blended composite will be performed each time the Surface changes.

**Comment by britzl** [comment]
@any-me thanks! We will start looking into this and similar issues with other extensions soon!
